services:
  app:
    build: .
    container_name: style-bert-vits2
    volumes:
      - .:/work
    ports:
      - "8000:7860"
      - "5000:5000"
      - "6006:6006"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: python server_fastapi.py
